# Generated by Django 5.1.2 on 2024-10-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pickled', models.BinaryField()),
                ('sent', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
